---
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3" FUTURE_PARSER="yes" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.0.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.1.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.2.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.3.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.4.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4.5.0" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=test
    - PUPPET_GEM_VERSION="~> 4" CHECK=rubocop

sudo: false

script: 'SPEC_OPTS="--format documentation" bundle exec rake $CHECK'

matrix:
  fast_finish: true

notifications:
  email: false
