name 'ghoneycutt-eyaml'
version '0.1.0'
source 'git://github.com/ghoneycutt/puppet-module-eyaml.git'
author 'ghoneycutt'
license 'Apache 2.0'
summary 'Manage hiera-eyaml'
description 'Manage hiera-eyaml'
project_page 'https://github.com/ghoneycutt/puppet-module-eyaml'

dependency 'puppetlabs/stdlib', '>= 4.2.0'
